### ISSUE TITLE
Melhoria do README

### ISSUE THREAD

**Issue by MChicoli** [mottapng/ES46B_HQ2#1]
Esta Modification Request (MR) tem como objetivo melhorar a apresentação do arquivo README.md do repositório. A intenção é utilizar recursos avançados do Markdown para tornar o conteúdo mais organizado e visualmente atrativo.

### Alterações Propostas:

- Adicionar cabeçalhos organizados para seções principais.
- Incluir listas ordenadas e não ordenadas para tópicos importantes.
- Utilizar tabelas para apresentação de informações estruturadas (se necessário).
- Melhorar a hierarquia e padronização dos títulos e subtítulos.

**Comment by PedroDonini** [comment]
MR Aprovado - 15/12/2024 às 14:42
