### ISSUE TITLE
Alterar o texto do botão de geração de ID

### ISSUE THREAD

**Issue by mottapng** [mottapng/ES46B_HQ2#3]
## Descrição

Atualmente, o botão de geração de ID na página [index.xhtml](https://github.com/mottapng/ES46B_HQ2/blob/804b4636b57a97c8ea0928c0dbc619de1a75707a/src/main/webapp/index.xhtml#L21) possui o texto "[]". Para melhorar a clareza e a usabilidade, o texto do botão deve ser alterado para "Gerar ID".

## Tarefas:

1. Abrir o arquivo [index.xhtml](https://github.com/mottapng/ES46B_HQ2/blob/804b4636b57a97c8ea0928c0dbc619de1a75707a/src/main/webapp/index.xhtml#L21).
2. Localizar o botão de geração de ID.
3. Alterar o valor do atributo value do botão de "[]" para "Gerar ID".
4. Salvar as alterações e confirmar que o texto do botão foi atualizado corretamente.

**Comment by MChicoli** [comment]
MR Aprovado - 16/12/2024 às 22:42

**Comment by MChicoli** [comment]
Arquivo bem organizado e funcional.
