### ISSUE TITLE
Alterar o tamanho da imagem "teamFriends"

### ISSUE THREAD

**Issue by PedroDonini** [mottapng/ES46B_HQ2#4]
# Descrição

Atualmente, a imagem teamFriends.png na página [index.xhtml](https://github.com/mottapng/ES46B_HQ2/blob/804b4636b57a97c8ea0928c0dbc619de1a75707a/src/main/webapp/index.xhtml#L21) precisa ser ajustada. Para melhorar a clareza e design da página, a imagem deverá ser levemente aumentada.

# Tarefas:
1. Abrir o arquivo [index.xhtml](https://github.com/mottapng/ES46B_HQ2/blob/804b4636b57a97c8ea0928c0dbc619de1a75707a/src/main/webapp/index.xhtml#L21).
2. Localizar a linha de código com a graphicImage de teamFriends.
3. Alterar o valor dos atributos "width" e "height" de forma a ajustar a imagem.
4. Salvar as alterações e confirmar que a imagem foi atualizada corretamente.

**Comment by mottapng** [comment]
MR Aprovado - 17/12/2024 às 15:51
